### ISSUE TITLE
Разное декодирование

### ISSUE THREAD

**Issue by MardeevRuslan** [rukhi7/binStrmParser#1]
![Разные](https://github.com/rukhi7/binStrmParser/assets/118975343/1daf1632-a69d-4e1f-bdc5-265e69293245)
Я только начал свой путь и мне нужно написать парсер, в первую очередь я начал поиск готовых решений.  Декодировка Вашего решения немного отличается от декодировки плагина VS code. Если Вас не затруднит и у Вас есть свободное время, объясните причины и подскажите как это можно пофиксить.

**Comment by rukhi7** [comment]
если вы имеете ввиду то что отображение кода 0х04 в символ разное, так это просто таблицы символов разные. Непонятно при чем здесь декодирование, что вы имеете в виду под словом "декодирование"- непонятно, поэтому.
Если вы бы написали на что влияет эта разница для вас, я думаю я бы смог вам помочь, тогда.
